// gitprofile.config.ts

const CONFIG = {
  github: {
    username: 'lucia-atienza', // Your GitHub org/user name. (This is the only required config)
  },
  /**
   * If you are deploying to https://<USERNAME>.github.io/, for example your repository is at https://github.com/arifszn/arifszn.github.io, set base to '/'.
   * If you are deploying to https://<USERNAME>.github.io/<REPO_NAME>/,
   * for example your repository is at https://github.com/arifszn/portfolio, then set base to '/portfolio/'.
   */
  base: '/',
  projects: {
    github: {
      display: true, // Display GitHub projects?
      header: 'Github Projects',
      mode: 'automatic', // Mode can be: 'automatic' or 'manual'
      automatic: {
        sortBy: 'stars', // Sort projects by 'stars' or 'updated'
        limit: 4, // How many projects to display.
        exclude: {
          forks: false, // Forked projects will not be displayed if set to true.
          projects: [], // These projects will not be displayed. example: ['arifszn/my-project1', 'arifszn/my-project2']
        },
      },
      manual: {
        // Properties for manually specifying projects
        projects: ['arifszn/gitprofile', 'arifszn/pandora'], // List of repository names to display. example: ['arifszn/my-project1', 'arifszn/my-project2']
      },
    },
    external: {
      // header: 'My Projects',
      // // To hide the `External Projects` section, keep it empty.
      // projects: [
      //   {
      //     title: 'Project Name',
      //     description:
      //       'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut.',
      //     imageUrl:
      //       'https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg',
      //     link: 'https://example.com',
      //   },
      //   {
      //     title: 'Project Name',
      //     description:
      //       'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod, nunc ut.',
      //     imageUrl:
      //       'https://img.freepik.com/free-vector/illustration-gallery-icon_53876-27002.jpg',
      //     link: 'https://example.com',
      //   },
      // ],
    },
  },
  seo: { title: 'Portfolio of Lucía Atienza Olmo', description: '', imageURL: '' },
  social: {
    linkedin: 'lucia-atienza-olmo',
    researchGate: '',
    facebook: '',
    instagram: '',
    reddit: '',
    threads: '',
    youtube: '', // example: 'pewdiepie'
    udemy: '',
    dribbble: '',
    behance: '',
    stackoverflow: '', // example: '1/jeff-atwood'
    discord: '',
    telegram: '',
    phone: '',
    email: 'atienzaolmolucia@gmail.com',
  },
  resume: {
    fileUrl:
      'https://drive.google.com/file/d/1GJDLA1SQt1uhhigx52R94jpqk1wyMeQ7/view?usp=sharing', // Empty fileUrl will hide the `Download Resume` button.
  },
  skills: [
    'Python',
    'SQL',
    'ETL',
    'Git',
    'Pandas',
    'NumPy',
    'Scikit-learn',
    'Matplotlib',
    'NLP',
    'TensorFlow'
  ],
  experiences: [
    {
      company: 'AppliedIT',
      position: 'Data Scientist',
      from: 'September 2024',
      to: 'Present',
      companyLink: 'https://applieditweb.com',
      description :  [
        "Integration of industrial systems through API queries, Python-based data processing, and SQL data persistence to enhance interoperability and efficiency.",
        "Integration of new aircraft models into existing frameworks for wing fault detection using advanced computer vision and machine learning techniques.",
        "Development of a predictive sales model for a bakery using machine learning. Leveraged Python along with pandas, scikit-learn, and matplotlib for data acquisition, cleansing, exploratory analysis, and model training.",
        "Design and implementation of a real-time industrial data acquisition and transmission system. Developed a Python application for the automated collection and synchronization of manufacturing data.",
        "Development of comprehensive ETL processes in Python for handling vehicle and inspection data, integrating results into SQL databases, and creating optimized SQL scripts for querying, insertion, and data updates.",
        "Design and development of a desktop tool capable of automatically identifying and documenting structural differences between XML files generated by industrial machinery."
    ]

    },
    {
      company: 'Accenture',
      position: 'Data Scientist',
      from: 'February 2024',
      to: 'September 2024',
      companyLink: 'https://accenture.com',
      description: [
        'Automatic processing and classification of emails using NLP and machine learning techniques. I participated in the development of an intelligent system for classifying emails into specific categories using natural language processing and machine learning techniques.'
      ],
    },
    {
      company: 'Abance',
      position: 'Software Engineer',
      from: 'July 2023',
      to: 'February 2024',
      companyLink: 'https://abance.es',
      description: [
        'Implementation of support for new recording format in naval mission viewer.'
      ],
    },
  ],
  certifications: [
    {
      // name: 'Lorem ipsum',
      // body: 'Lorem ipsum dolor sit amet',
      // year: 'March 2022',
      // link: 'https://example.com',
    },
  ],
  educations: [
    {
      institution: 'University of Cádiz',
      degree: 'Computer Science Engineering',
      from: '2019',
      to: '2024',
    },
  ],
  publications: [
    {
      title: 'Detection of cyberbullying on the internet and social media using natural language processing techniques',
      conferenceName: '',
      journalName: '',
      authors: 'Atienza-Olmo, L. supervised by Guerrero-Contreras G.',
      link: 'https://rodin.uca.es/handle/10498/34029',
      description:
        "Cyberbullying has become a serious problem in today's society, causing a significant impact on victims. In this context, the potential of artificial intelligence as a possible tool for addressing these abusive behaviours in digital media becomes relevant. This final degree project studies natural language processing and machine learning techniques for detecting cyberbullying on the internet and social networks. Different models capable of detecting offensive content in internet texts will be developed, such as LGBM, BERT and hybrid models that incorporate metadata extracted from the text. The datasets used will consist of tweets in Spanish and English, with the aim of comparing the results and dynamics of cyberbullying in different linguistic contexts. The metadata extracted from the text will be based on the study and extraction of linguistic patterns representative of cyberbullying. The results of the different models obtain a range of F1-score values between 0.7 and 0.94, indicating their high performance, with the results of the hybrid models being particularly relevant. These obtain considerable improvements over the other models, indicating that the metadata adds contextual information that allows them to make better predictions. This phenomenon is evident in both data sets, regardless of language, reinforcing the validity of the finding. This project demonstrates the usefulness of artificial intelligence as a tool for detecting cyberbullying, which is particularly useful for moderating content on the internet and social media.",
    },
    
  ],
  // Display articles from your medium or dev account. (Optional)
  blog: {
    // source: 'dev', // medium | dev
    // username: 'arifszn', // to hide blog section, keep it empty
    // limit: 2, // How many articles to display. Max is 10.
  },
  googleAnalytics: {
    id: '', // GA3 tracking id/GA4 tag id UA-XXXXXXXXX-X | G-XXXXXXXXXX
  },
  // Track visitor interaction and behavior. https://www.hotjar.com
  hotjar: { id: '', snippetVersion: 6 },
  themeConfig: {
    defaultTheme: 'pastel',

    // Hides the switch in the navbar
    // Useful if you want to support a single color mode
    disableSwitch: false,

    // Should use the prefers-color-scheme media-query,
    // using user system preferences, instead of the hardcoded defaultTheme
    respectPrefersColorScheme: false,

    // Display the ring in Profile picture
    displayAvatarRing: true,

    // Available themes. To remove any theme, exclude from here.
    themes: [
      'light',
      'dark',
      'cupcake',
      'bumblebee',
      'emerald',
      'corporate',
      'synthwave',
      'retro',
      'cyberpunk',
      'valentine',
      'halloween',
      'garden',
      'forest',
      'aqua',
      'lofi',
      'pastel',
      'fantasy',
      'wireframe',
      'black',
      'luxury',
      'dracula',
      'cmyk',
      'autumn',
      'business',
      'acid',
      'lemonade',
      'night',
      'coffee',
      'winter',
      'dim',
      'nord',
      'sunset',
      'caramellatte',
      'abyss',
      'silk',
      'procyon',
    ],
  },

  // Optional Footer. Supports plain text or HTML.
  footer: `Made with <a 
      class="text-primary" href="https://github.com/arifszn/gitprofile"
      target="_blank"
      rel="noreferrer"
    >GitProfile</a> and ❤️`,

  enablePWA: true,
};

export default CONFIG;
